import type { GramPathway, Item, IngredientRow } from '@nutai/core-schema'

/**
 * Confidence and calibration.
 *
 * docs/inherited-design.md I §7.
 *
 * WHY THE MODEL'S OWN CONFIDENCE NUMBER IS NOT THE ANSWER.
 *
 * Verbalized LLM confidence is measurably miscalibrated. Xiong et al.,
 * "Can LLMs Express Their Uncertainty?" (arXiv:2306.13063), finds models "tend to
 * be overconfident, potentially imitating human patterns of expressing
 * confidence", and that black-box confidence elicitation trails white-box
 * internal-probability methods by an AUROC gap of 0.522 to 0.605.
 *
 * Under bring-your-own-key we never see token probabilities — we get back
 * whatever JSON the API returns — so we are STRUCTURALLY CONFINED to the worse
 * side of that gap. Small-classifier softmax has the mirror-image problem:
 * overconfident without temperature scaling.
 *
 * So the model's self-report is a MODIFIER, never the signal. The primary signal
 * is measured per-pathway and per-category error from our own eval harness.
 *
 * And the bar to clear is not "perfectly calibrated Bayesian intervals". The
 * incumbent shows no confidence score, error range, or uncertainty indicator of
 * any kind, while its FAQ concedes "CalAI is about 80% accurate" and its blog
 * boilerplate claims 90% — two different self-reported numbers from one company,
 * neither per-scan, neither sourced. The bar is showing ANY honest measured
 * signal at all.
 */

export type FoodCategory =
  | 'whole_food'
  | 'packaged_labeled'
  | 'simple_cooked'
  | 'mixed_composite'
  | 'hidden_fat_likely'
  | 'liquid'

export type InferencePath = 'cloud' | 'local'

export type BandTier = 'none' | 'tight' | 'moderate' | 'wide' | 'very_wide'

export interface Band {
  halfPct: number
  tier: BandTier
  /** Plain-language reasons, shown when the user taps the confidence chip. */
  reasons: string[]
}

/** Never display a band wider than this — past it, say it in words instead. */
export const MAX_DISPLAYED_HALF_PCT = 0.6

/**
 * Measured baselines, shipped as DATA and regenerated by the eval harness.
 *
 * Before the harness has ever run this ships seeded from the §4.9 literature
 * table, every value traceable to a cited MAPE/PMAE figure. The file records
 * which values are measured and which are still seeded, and the "How accurate is
 * this?" page shows that distinction — because claiming a measured number we have
 * not measured would be the exact dishonesty this product exists to avoid.
 */
export interface MeasuredBaselines {
  pathwayHalfPct: Record<GramPathway, number>
  categoryHalfPct: Record<FoodCategory, number>
  localPathMultiplier: number
  provenance: Record<string, 'seeded' | 'measured'>
  generatedAt: string | null
}

export const SEEDED_BASELINES: MeasuredBaselines = {
  pathwayHalfPct: {
    packaged_exact: 0.02,
    discrete_count: 0.125,
    personal_prior: 0.1,
    geometry_exact_ref: 0.175,
    geometry_soft_ref: 0.275,
    fndds_standard_portion: 0.375,
    container_fill: 0.325,
    model_guess: 0.375,
    clamped: 0.5,
    user_edited: 0.0,
  },
  categoryHalfPct: {
    whole_food: 0.15,
    packaged_labeled: 0.03,
    simple_cooked: 0.25,
    mixed_composite: 0.45,
    hidden_fat_likely: 0.4,
    liquid: 0.3,
  },
  localPathMultiplier: 1.3,
  provenance: { all: 'seeded' },
  generatedAt: null,
}

export function bandTier(halfPct: number): BandTier {
  if (halfPct <= 0.05) return 'none'
  if (halfPct <= 0.15) return 'tight'
  if (halfPct <= 0.3) return 'moderate'
  if (halfPct <= 0.45) return 'wide'
  return 'very_wide'
}

/**
 * The confidence vocabulary. Deliberately NOT a colour scale.
 *
 * Uncertainty renders violet, never amber or red. Red is reserved for safety
 * warnings only. Low confidence is an invitation to check, not a scold — and a
 * scolding colour is what makes people switch the indicator off, which defeats
 * the entire point of having one.
 */
export const TIER_GLYPH: Record<BandTier, string> = {
  none: '●',
  tight: '◕',
  moderate: '◑',
  wide: '◔',
  very_wide: '○',
}

export function classifyCategory(item: Item): FoodCategory {
  if (item.legible_label_text != null) return 'packaged_labeled'
  if (item.is_beverage || item.food_form === 'liquid') return 'liquid'

  const key = item.canonical_food_key.toLowerCase()
  if (/\b(stir.?fry|curry|fried rice|saute|sautee|casserole|stew|lasagna|risotto|pad thai)\b/.test(key)) {
    return 'mixed_composite'
  }
  if (
    item.cooking_method_cues.includes('deep_fried_color') ||
    item.cooking_method_cues.includes('visible_oil_pooling') ||
    item.cooking_method_cues.includes('batter_or_breading')
  ) {
    return 'hidden_fat_likely'
  }
  if (item.cooking_method_cues.some((c) => c !== 'none_visible' && c !== 'raw')) {
    return 'simple_cooked'
  }
  return 'whole_food'
}

export function isGroundMeat(item: Item): boolean {
  return /\b(ground beef|ground meat|mince|burger|meatball|meatloaf)\b/.test(
    item.canonical_food_key.toLowerCase(),
  )
}
export function isPouredAlcohol(item: Item): boolean {
  return item.beverage_category === 'alcoholic_poured_or_mixed'
}
export function isBlendedShake(item: Item): boolean {
  return item.beverage_category === 'blended_shake_or_smoothie'
}
export function isDeepFried(item: Item): boolean {
  return (
    item.cooking_method_cues.includes('deep_fried_color') ||
    item.cooking_method_cues.includes('batter_or_breading')
  )
}

export interface SecondOpinionResult {
  gramsFor(rowId: string): number | null
}

export interface ComputeBandInput {
  row: IngredientRow
  item: Item
  baselines: MeasuredBaselines
  path: InferencePath
  priorSampleCount?: number | undefined
  priorRatioVariance?: number | undefined
  secondOpinion?: SecondOpinionResult | undefined
  hadClampFlag?: boolean | undefined
}

/** Steps 1-8 of §7.2, in order. */
export function computeBand(input: ComputeBandInput): Band {
  const { row, item, baselines, path } = input
  const reasons: string[] = []

  // 1. PRIMARY — measured half-width for the gram pathway actually used. Taken
  //    from the harness, not invented.
  let half = baselines.pathwayHalfPct[row.gramPathway] ?? 0.4

  // 2. Category widening. A mixed dish is harder than its pathway suggests.
  const cat = classifyCategory(item)
  const catHalf = baselines.categoryHalfPct[cat]
  if (catHalf > half) {
    half = catHalf
    if (cat === 'mixed_composite') reasons.push('Mixed dishes are harder to estimate accurately.')
    if (cat === 'hidden_fat_likely') reasons.push('Cooking oil is not visible in a photo.')
  }

  // 3. Food-class widening for known structural variance.
  if (isGroundMeat(item)) {
    half *= 1.15
    reasons.push('Ground meat loses 62-77% of its weight cooking, depending on fat content.')
  }
  if (isPouredAlcohol(item)) {
    half *= 1.35
    reasons.push('The alcohol content of a poured drink is not visible.')
  }
  if (isBlendedShake(item)) {
    half *= 1.35
    reasons.push('A blended drink’s recipe is not visible.')
  }
  if (isDeepFried(item)) {
    half *= 1.15
    reasons.push('Fried food absorbs 10-28% of its weight in oil.')
  }

  // 4. MODIFIER ONLY — the model's own portion confidence. It never replaces the
  //    measured baseline. Its absolute scale is uncalibrated, but it does
  //    correlate with genuine difficulty, so it earns a nudge and nothing more.
  if (item.portion_confidence < 0.4) {
    half *= 1.5
    reasons.push('The model said it was unsure about this portion.')
  } else if (item.portion_confidence > 0.8) {
    half *= 0.85
  }

  // 5. Path widening. The local path's closed vocabulary is a real constraint,
  //    not an arbitrary penalty.
  if (path === 'local') half *= baselines.localPathMultiplier

  // 6. Personal-prior narrowing — the ONLY mechanism that can beat the population
  //    baseline, and only on demonstrated consistency.
  if (
    input.priorSampleCount != null &&
    input.priorSampleCount >= 5 &&
    (input.priorRatioVariance ?? 1) < 0.05
  ) {
    half = Math.min(half, baselines.pathwayHalfPct.personal_prior)
    reasons.push('Narrowed because your own logs for this food are consistent.')
  }

  // 7. Empirical agreement — the one genuinely measured per-scan signal, when the
  //    user has paid for a second opinion.
  const second = input.secondOpinion?.gramsFor(row.id)
  if (second != null && second > 0) {
    const relDiff = Math.abs(row.grams - second) / Math.max(row.grams, second)
    if (relDiff < 0.15) {
      half *= 0.6
      reasons.push('Two models independently agreed on this portion.')
    } else {
      half *= 1.3
      reasons.push('Two models disagreed on this portion.')
    }
  }

  // 8. Clamp flags and generic fallbacks FLOOR the band. They never narrow it.
  if (row.gramPathway === 'clamped' || input.hadClampFlag === true) {
    half = Math.max(half, 0.5)
    reasons.push('Something about this estimate looked out of range — please check it.')
  }

  return {
    halfPct: Math.min(half, MAX_DISPLAYED_HALF_PCT),
    tier: bandTier(Math.min(half, MAX_DISPLAYED_HALF_PCT)),
    reasons,
  }
}

export interface BandedItem {
  kcal: number
  band: Band
}

/**
 * Per-meal, errors COMPOUND and must not be averaged.
 *
 * A meal band is not the mean of item bands. Independent-ish item errors combine
 * in quadrature, weighted by each item's calorie contribution — so one uncertain
 * side salad does not drag down a meal dominated by a labeled packaged item, and
 * one uncertain main course is not diluted by three confident small sides.
 */
export function mealBand(items: readonly BandedItem[]): Band {
  const total = items.reduce((s, i) => s + i.kcal, 0)
  if (total === 0 || items.length === 0) return { halfPct: 0, tier: 'none', reasons: [] }

  const variance = items.reduce((acc, i) => {
    const w = i.kcal / total
    return acc + (w * i.band.halfPct) ** 2
  }, 0)
  let half = Math.sqrt(variance)

  // FLOOR: a meal is never presented as more certain than its single
  // largest-calorie contributor, whatever the quadrature arithmetic says.
  const dominant = items.reduce((a, b) => (a.kcal > b.kcal ? a : b))
  half = Math.max(half, dominant.band.halfPct * 0.7)

  const reasons = [...new Set(items.flatMap((i) => i.band.reasons))]
  const capped = Math.min(half, MAX_DISPLAYED_HALF_PCT)
  return { halfPct: capped, tier: bandTier(capped), reasons }
}

/** The displayed range for a value, at its band. */
export function rangeFor(value: number, band: Band): { low: number; high: number } {
  return { low: value * (1 - band.halfPct), high: value * (1 + band.halfPct) }
}
